### ISSUE TITLE
Change extra props mechanism from a dictionary to a bool

### ISSUE THREAD

**Issue by anotherstarburst** [komlasapaty/datastore-entity#4]
I originally had this as an aside in https://github.com/komlasapaty/datastore-entity/issues/2 but thought it might distract the thread... so here's a stand-alone ticket we can discuss :)

We know that a given `kind` can have a mix of property definitions. I agree with your decision to need to **explicitly** allow additional properties as

```
name = "anotherstarburst"
user.save(extra_props={"name": name})
```

However, consider a model definition that starts out as 

```
class User(DatastoreEntity):
    email = EntityValue(None)
```

Over time this might change to

```
class User(DatastoreEntity):
    email = EntityValue(None)
    name = EntityValue(None)
```

If we then want our user to be able to update/change their name. With the current `datastore-entity` implementation this would look something like  

```
name = "anotherstarburst"
if isinstance(user.name, EntityValue):
    user.save(extra_props={"name": name})
else:
    user.name = name
    user.save()
```

I'd propose deprecating `extra_props` in favour of a boolean `save_extra_props` such that if any props have been added to the object instance they're automatically added to the object persisted in datastore. That way you would have

```
user.name = "anotherstarburst"
user.save(save_extra_props=True)
```

This allows fine grained control for people that don't want to automatically have extra properties added to their objects. However, it also makes adding extra properties for "mixed" entities of the same kind a bit cleaner.

If you agree with this direction I'd be happy to give it a shot?

**Comment by komlasapaty** [comment]
Thanks for looking at this. 
Your example is indeed elegant!

The reason why addition of extra properties is explicit is because not all object attributes will necessarily be entity properties.
For example, there are times when a model definition will use multiple inheritance(eg. when using Flask-Login's UserMixin class for a User model). 

So to avoid this, I made object attributes that are supposed to be entity properties explicit.
So when we do `user.name = 'anotherstarburst'` and then call `save(save_extra_props=True`), is there a straightforward way to pick only the `name` attribute leaving all other attributes of the object that are not supposed to be properties?

It's also the reason property values are marked with the EntityValue class.
It means that the following will work now:
```
user.name = EntityValue('anotherstarbust')  #additional property
user.save()
```
Except that using a dictionary allows for multiple properties to be added in a 'concise' way.

What do you think?
Maybe the implementation is not doing proper class instrospection?

**Comment by anotherstarburst** [comment]
I understand what you're saying. Having the `UserMixin` or any other parent class does potentially complicate matters. Did this come up during your smoke testing of the library? i.e. did you find that keys from the UserMixin class were being persisted as properties of the object?

I recall not facing this issue using [ndb](https://googleapis.dev/python/python-ndb/latest/) for the python2 implementation a few years ago. I've had a quick skim through the code and can't see how they differentiate between the properties, or if they do.

    user.name = EntityValue('anotherstarbust')  #additional property

Do you mean to say this should work now? I've tried a quick test run but it didn't seem to work.

If it does work, and I'm just not implementing it correctly, it is definitely an improvement on my earlier approach. A downside is of course that, over time, the codebase would be littered with EntityValue for safety ... just in case there exist any entities without a particular property.

**Comment by komlasapaty** [comment]
Yeah, properties from the `UserMixin` (eg `is_active`) were showing up as entity properties.

[ndb](https://googleapis.dev/python/python-ndb/latest/model.html) also defines their own model types.
SQLAlchemy define theirs own types too.

I'll take a look at the example above to see where the problem is.

I appreciate you taking time to look at this.

**Comment by komlasapaty** [comment]
I have made an update to support the pattern you suggested.

The examples on the documentation have also been updated.

Thanks a lot.

**Comment by anotherstarburst** [comment]
Dude, that is awesome! Thank you for this - it's going to make using the library a lot cleaner :)

Closed with a code change. Documentation detailing the updated implementation added in commit: https://github.com/komlasapaty/datastore-entity/commit/a00e0431c422030ebd02d9c2f6fcca2ae4802e3b
